//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team2_POP.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Team2_POP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_CircleGreen {
            get {
                object obj = ResourceManager.GetObject("Img_CircleGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_CircleRed {
            get {
                object obj = ResourceManager.GetObject("Img_CircleRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_CircleYellow {
            get {
                object obj = ResourceManager.GetObject("Img_CircleYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Close {
            get {
                object obj = ResourceManager.GetObject("Img_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Error {
            get {
                object obj = ResourceManager.GetObject("Img_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Exit {
            get {
                object obj = ResourceManager.GetObject("Img_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Information {
            get {
                object obj = ResourceManager.GetObject("Img_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LeftArrow {
            get {
                object obj = ResourceManager.GetObject("Img_LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_LeftButton {
            get {
                object obj = ResourceManager.GetObject("Img_LeftButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Logo {
            get {
                object obj = ResourceManager.GetObject("Img_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Logout {
            get {
                object obj = ResourceManager.GetObject("Img_Logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon IMG_POPMain {
            get {
                object obj = ResourceManager.GetObject("IMG_POPMain", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Producing {
            get {
                object obj = ResourceManager.GetObject("Img_Producing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_RightArrow {
            get {
                object obj = ResourceManager.GetObject("Img_RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_RightButton {
            get {
                object obj = ResourceManager.GetObject("Img_RightButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Success {
            get {
                object obj = ResourceManager.GetObject("Img_Success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Warning {
            get {
                object obj = ResourceManager.GetObject("Img_Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {0}를 선택해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgChoice1 {
            get {
                return ResourceManager.GetString("MsgChoice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}을 선택해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgChoice2 {
            get {
                return ResourceManager.GetString("MsgChoice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgCommonResultFailHeader {
            get {
                return ResourceManager.GetString("MsgCommonResultFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택하신 불량번호 : {0} 
        ///처리하지 못하었습니다. 
        ///다시시도해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDefectiveResultFailContents {
            get {
                return ResourceManager.GetString("MsgDefectiveResultFailContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량등록 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDefectiveResultFailHeader {
            get {
                return ResourceManager.GetString("MsgDefectiveResultFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택하신 불량번호 : {0} 
        ///불량유형 : {1} 
        ///불량처리 : {2}상태
        ///위에 정보로 정상처리 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDefectiveResultSucceesContents {
            get {
                return ResourceManager.GetString("MsgDefectiveResultSucceesContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량등록 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDefectiveResultSucceesHeader {
            get {
                return ResourceManager.GetString("MsgDefectiveResultSucceesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 불량내역을 처리했습니다. 
        ///해당폼이 닫힙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDefectiveSaveAsAllCompleteContent {
            get {
                return ResourceManager.GetString("MsgDefectiveSaveAsAllCompleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택되지 않은 값 존재과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDefectiveValidate {
            get {
                return ResourceManager.GetString("MsgDefectiveValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비가동 데이터가 존재하지 않습니다. 
        ///다시 시도하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDowntimeGetResultFailContent {
            get {
                return ResourceManager.GetString("MsgDowntimeGetResultFailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비가동 불러오기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDowntimeGetResultFailHeader {
            get {
                return ResourceManager.GetString("MsgDowntimeGetResultFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비가동처리가 정상적으로 등록되지않았습니다. 
        ///다시 시도해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDowntimeSetResultFailContent {
            get {
                return ResourceManager.GetString("MsgDowntimeSetResultFailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비가동 등록 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgDowntimeSetResultFailHeader {
            get {
                return ResourceManager.GetString("MsgDowntimeSetResultFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오늘보다 큰 날짜의 작업은 조회할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgGetDateLoadFailContent {
            get {
                return ResourceManager.GetString("MsgGetDateLoadFailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜 불러오기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgGetDateLoadFailHeader {
            get {
                return ResourceManager.GetString("MsgGetDateLoadFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 불러오기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgLoadResultFailHeader {
            get {
                return ResourceManager.GetString("MsgLoadResultFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실적 목록을 선택해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgPerformanceSelectFailContent {
            get {
                return ResourceManager.GetString("MsgPerformanceSelectFailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 선택 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgPerformanceSelectFailHeader {
            get {
                return ResourceManager.GetString("MsgPerformanceSelectFailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산데이터를 불러오는 중에 실패했습니다. 
        ///다시 시도하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceListLoadFailContent {
            get {
                return ResourceManager.GetString("MsgProduceListLoadFailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산을 시작합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceStartAcceptSucceesContent {
            get {
                return ResourceManager.GetString("MsgProduceStartAcceptSucceesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접수 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceStartAcceptSucceesHeader {
            get {
                return ResourceManager.GetString("MsgProduceStartAcceptSucceesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기계와의 작동이 원할하지 않습니다. 
        ///기계서버의 상태를 점검한 후 다시 시도해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceStartConnectResultContent {
            get {
                return ResourceManager.GetString("MsgProduceStartConnectResultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기계통신 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceStartConnectResultHeader {
            get {
                return ResourceManager.GetString("MsgProduceStartConnectResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;처리하는 과정에서 오류가 발생하였습니다.
        ///다시 시도해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceStartLengthFailContent {
            get {
                return ResourceManager.GetString("MsgProduceStartLengthFailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산실적을 선택해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceStartResultContent {
            get {
                return ResourceManager.GetString("MsgProduceStartResultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgProduceStartResultHeader {
            get {
                return ResourceManager.GetString("MsgProduceStartResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최신버젼의 업데이트가 있습니다.
        ///업데이트 적용을 위해 프로그램을 재시작합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgUpdateResultContent {
            get {
                return ResourceManager.GetString("MsgUpdateResultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgUpdateResultHeader {
            get {
                return ResourceManager.GetString("MsgUpdateResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}의 생산되지 않은 작업이
        ///이미 할당되어 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgWorkerSetFailResultContent {
            get {
                return ResourceManager.GetString("MsgWorkerSetFailResultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업자 설정 {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgWorkerSetResultHeader {
            get {
                return ResourceManager.GetString("MsgWorkerSetResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산번호 : {0}를 
        ///작업자 : {1}에게 할당했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgWorkerSucceesContent {
            get {
                return ResourceManager.GetString("MsgWorkerSucceesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업날짜 : {0} 
        ///공정 : {1} 
        ///위의 작업내역이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgWorkResultNullContent {
            get {
                return ResourceManager.GetString("MsgWorkResultNullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업내역 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgWorkResultNulllHeader {
            get {
                return ResourceManager.GetString("MsgWorkResultNulllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 생산 {
            get {
                object obj = ResourceManager.GetObject("생산", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
